### PR TITLE
rename

### PR DESCRIPTION
**Pull request by sccolbert**
cc @jasongrout

### CODE REVIEW

**Comment by jasongrout** [comment]
Better, but I still think `scrollIntoViewNearest` is a better name - it conveys the appropriate specialization, and avoids this ambiguous "need" that is supposedly being filled.

**Comment by sccolbert** [comment]
you're killing me smalls.

**Comment by jasongrout** [comment]
Just trying to live up to your standard of quality :)

**Comment by sccolbert** [comment]
I update the docs to indicate what  `IfNeeded` means. I don't think `Nearest` is much more descriptive. Going to leave it as-is in this PR.

**Comment by jasongrout** [comment]
> I updated the docs to indicate what IfNeeded means. I don't think Nearest is much more descriptive. Going to leave it as-is in this PR.

Okay, you're call.

**Comment by jasongrout** [comment]
just noticed the branch title. Oh well :).

**Pull request merged**
