### PR TITLE
don't conflict with website docs examples dir that hold the index

### PR DESCRIPTION
**Pull request by Carreau**
I really need to find a better way to build docs. 

I've pushed changes on the docs website to accomodate for that.

### CODE REVIEW

**Comment by sccolbert** [comment]
@Carreau  What exactly is the problem?

**Comment by sccolbert** [comment]
This PR is throwing 401 errors on Travis. Do you have any idea why?

**Comment by Carreau** [comment]
> This PR is throwing 401 errors on Travis. Do you have any idea why?

Yes, it is because the token cannot be decrypted on travis in PRs, to `tds resintall -so` get rate limitted.
secret are not decrypted on PR otherwise anybody submitting a PR could just 'echo DECRYPTED_TOKEN' on do things on your behalf. Token only get decrypted once merged in master.  

I'm dont' know if there is a way around that, if we can have something similar without actually hitting github. Or generate a token that we allow to be decrypted on PR and that have no-access to anything, except increase github API rate limit.

**Comment by sccolbert** [comment]
This is no longer needed since this repo now only builds the API docs.

**Pull request closed without merging**
