### PR TITLE
Upgrade Lerna and separate version bump from publish

### LINKED ISSUE #386: npm package dependency is broken
`@phosphor/widgets@1.7.0` depends on `@phosphor/disposable@^1.1.3` which is not found in npmjs.com.

This would cause installing a jupyter related package to raise an error like `No matching version found for @phosphor/disposable@^1.1.3`

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #386

### CODE REVIEW

**Comment by sccolbert** [comment]
Did you need me to do something before you merge this?

**Comment by blink1073** [comment]
Ha, meant to ping @afshin or @jasongrout for review, but feel free!

**Comment by afshin** [comment]
When I check out this branch, I have test failures. I can see it has passed the CI, so it's probably my fault and/or setup.

Do the tests work for you?

<details>
<summary>Here is my error output...</summary>
<pre>
SUMMARY:
✔ 760 tests completed
✖ 34 tests failed

FAILED TESTS:
  @phosphor/widgets
    FocusTracker
      #currentChanged
        ✖ should be emitted when the current widget has changed
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected null to not equal null
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:30503:48


      #activeChanged
        ✖ should be emitted when the active widget has changed
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected null to not equal null
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:30534:48


        ✖ should be emitted when the active widget is set to null
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected null to not equal null
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:30548:48


      #currentWidget
        ✖ should be set to the widget that gained focus
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected { Object (_flags, _layout, ...) } to equal { Object (_flags, _layout, ...) }
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:30587:57


        ✖ should revert to the previous widget if the current widget is removed
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected { Object (_flags, _layout, ...) } to equal { Object (_flags, _layout, ...) }
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:30597:57


      #activeWidget
        ✖ should be set to `null` when the active widget loses focus
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected { Object (_flags, _layout, ...) } to equal null
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:30627:56


        ✖ should be set to the widget that gained focus
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected { Object (_flags, _layout, ...) } to equal { Object (_flags, _layout, ...) }
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:30638:56


      #focusNumber()
        ✖ should give the highest number for the currentWidget
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected -1 to equal 1
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:30677:64


        ✖ should update when a widget gains focus
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected 0 to equal 2
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:30698:64


      #remove()
        ✖ should set the currentWidget to the previous one if the widget is the currentWidget
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected { Object (_flags, _layout, ...) } to equal { Object (_flags, _layout, ...) }
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:30759:57


    TabBar
      #tabMoved
        ✖ should be emitted when a tab is moved right by the user
          Firefox 67.0.0 (Mac OS X 10.14.0)
        Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

        ✖ should be emitted when a tab is moved left by the user
          Firefox 67.0.0 (Mac OS X 10.14.0)
        Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

      #tabActivateRequested
        ✖ should be emitted when a tab is left pressed by the user
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected false to equal true
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:34855:42


        ✖ should make the tab current and emit the `currentChanged` signal
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected 1 to equal 2
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:34865:52


        ✖ should emit even if the pressed tab is the current tab
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected false to equal true
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:34876:42


      #tabCloseRequested
        ✖ should be emitted when a tab close icon is left clicked
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected false to equal true
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:34899:42


        ✖ should be emitted when a tab is middle clicked
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected false to equal true
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:34912:42


      #tabDetachRequested
        ✖ should be emitted when a tab is dragged beyond the detach threshold
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected false to equal true
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:34953:42


        ✖ should be handled by calling `releaseMouse` and removing the tab
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected false to equal true
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:34965:42


        ✖ should only be emitted once per drag cycle
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected 0 to equal 1
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:34977:42


        ✖ should add the `p-mod-dragging` class to the tab and the bar
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected false to equal true
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:34991:42


      #allowDeselect
        ✖ should determine whether a tab can be deselected by the user
          Firefox 67.0.0 (Mac OS X 10.14.0)
        expected 2 to equal -1
        AssertionError@build/bundle.test.js:20952:13
        module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
        assertEqual@build/bundle.test.js:39290:12
        module.exports/ctx[name]@build/bundle.test.js:42726:25
        @build/bundle.test.js:35036:52


      #handleEvent()
        left click
          ✖ should emit a tab close requested signal
            Firefox 67.0.0 (Mac OS X 10.14.0)
          expected false to equal true
          AssertionError@build/bundle.test.js:20952:13
          module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
          assertEqual@build/bundle.test.js:39290:12
          module.exports/ctx[name]@build/bundle.test.js:42726:25
          @build/bundle.test.js:35409:46


        middle click
          ✖ should emit a tab close requested signal
            Firefox 67.0.0 (Mac OS X 10.14.0)
          expected false to equal true
          AssertionError@build/bundle.test.js:20952:13
          module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
          assertEqual@build/bundle.test.js:39290:12
          module.exports/ctx[name]@build/bundle.test.js:42726:25
          @build/bundle.test.js:35451:46


        mousedown
          ✖ should add event listeners if the tabs are movable
            Firefox 67.0.0 (Mac OS X 10.14.0)
          expected -1 to not equal -1
          AssertionError@build/bundle.test.js:20952:13
          module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
          assertEqual@build/bundle.test.js:39290:12
          module.exports/ctx[name]@build/bundle.test.js:42726:25
          @build/bundle.test.js:35485:75


        mousemove
          ✖ should do nothing if there is a drag in progress
            Firefox 67.0.0 (Mac OS X 10.14.0)
          expected 0 to equal 1
          AssertionError@build/bundle.test.js:20952:13
          module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
          assertEqual@build/bundle.test.js:39290:12
          module.exports/ctx[name]@build/bundle.test.js:42726:25
          @build/bundle.test.js:35525:46


          ✖ should emit the detach requested signal if the threshold is exceeded
            Firefox 67.0.0 (Mac OS X 10.14.0)
          expected false to equal true
          AssertionError@build/bundle.test.js:20952:13
          module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
          assertEqual@build/bundle.test.js:39290:12
          module.exports/ctx[name]@build/bundle.test.js:42726:25
          @build/bundle.test.js:35553:46


          ✖ should bail if the signal handler aborted the drag
            Firefox 67.0.0 (Mac OS X 10.14.0)
          expected false to equal true
          AssertionError@build/bundle.test.js:20952:13
          module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
          assertEqual@build/bundle.test.js:39290:12
          module.exports/ctx[name]@build/bundle.test.js:42726:25
          @build/bundle.test.js:35564:46


          ✖ should update the positions of the tabs
            Firefox 67.0.0 (Mac OS X 10.14.0)
          expected false to equal true
          AssertionError@build/bundle.test.js:20952:13
          module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
          assertEqual@build/bundle.test.js:39290:12
          module.exports/ctx[name]@build/bundle.test.js:42726:25
          @build/bundle.test.js:35575:46


        mouseup
          ✖ should emit the `tabMoved` signal
            Firefox 67.0.0 (Mac OS X 10.14.0)
          Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

          ✖ should move the tab to its final position
            Firefox 67.0.0 (Mac OS X 10.14.0)
          Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

          ✖ should cancel a middle mouse release
            Firefox 67.0.0 (Mac OS X 10.14.0)
          expected false to equal true
          AssertionError@build/bundle.test.js:20952:13
          module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
          assertEqual@build/bundle.test.js:39290:12
          module.exports/ctx[name]@build/bundle.test.js:42726:25
          @build/bundle.test.js:35600:49


        keydown
          ✖ should prevent default
            Firefox 67.0.0 (Mac OS X 10.14.0)
          expected false to equal true
          AssertionError@build/bundle.test.js:20952:13
          module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
          assertEqual@build/bundle.test.js:39290:12
          module.exports/ctx[name]@build/bundle.test.js:42726:25
          @build/bundle.test.js:35608:49


        contextmenu
          ✖ should prevent default
            Firefox 67.0.0 (Mac OS X 10.14.0)
          expected false to equal true
          AssertionError@build/bundle.test.js:20952:13
          module.exports/Assertion.prototype.assert@build/bundle.test.js:38773:13
          assertEqual@build/bundle.test.js:39290:12
          module.exports/ctx[name]@build/bundle.test.js:42726:25
          @build/bundle.test.js:35622:49


info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run test stderr:
npm WARN lifecycle The node binary used for scripts is /var/folders/r_/v_6fh4dj3cs480pt8g0xypg40000gn/T/yarn--1560117197687-0.6881165568354579/node but npm is using ~/.nvm/versions/node/v12.2.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @phosphor/widgets@1.7.0 test:firefox: `cd tests && karma start --browsers=Firefox`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @phosphor/widgets@1.7.0 test:firefox script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
error Command failed with exit code 1.

lerna ERR! yarn run test exited 1 in '@phosphor/widgets'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `lerna run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
</pre>
</details>

**Comment by afshin** [comment]
Hm, I checked another branch and I still experience this failure. I think it must have something to do with my environment, but I'm curious if it works for you.

**Comment by afshin** [comment]
It turns out that Firefox tests fail in my environment (macOS 10.14.5 and Firefox 67.0.1).

Chrome tests pass.

**Comment by afshin** [comment]
Since this happens in `master`, I've opened a new issue as this is unrelated to this PR: https://github.com/phosphorjs/phosphor/issues/388

**Pull request merged**
