### PR TITLE
[WIP] Build example and deploy on travis.

### PR DESCRIPTION
**Pull request by Carreau**
It kinda-work on my fork, but I need to polish rough edges. 

Travis also got Github-request throttled. 

I could also integrate with http://typedoc.io/ to get doc autobuild on every push.

I'll rebase and squash the commits later.

### CODE REVIEW

**Comment by Carreau** [comment]
Right ! it [works](http://carreau.github.io/phosphor/examples/boxpanel/) ! 

Litlle ugly, had to workaround github being DDOS'ed, so blocking some requests.

**Comment by Carreau** [comment]
(last commit add the type definitions and remove the `tds reinstall -so`, but need to be reverted)

**Comment by Carreau** [comment]
[docs](http://carreau.github.io/phosphor/docs/) also build.

**Comment by bollwyvl** [comment]
Good stuff... was thinking the same way, but hadn't thought about the publishing and multiple groups route. Also tinkering with a docker machine, as i find the build chain a little weird... typings etc. as you discovered. Interested to get a good look at it, a little disappointed about yet another package manager for javascript required.

**Comment by Carreau** [comment]
Yeah... We'll see. Trying to automatize as much as possible to lower friction and things I actually have to remember.

Also playing with design a bit to change from code.

capture d ecran 2015-03-26 a 22 44 24

**Comment by bollwyvl** [comment]
Some takes on green, rather than React Teal™

**Comment by Carreau** [comment]
Any clue why tsd reinstall 403 on `https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master` from travis and not locally. 

Maybe @sccolbert know another way to get the types definitions ?

**Comment by sccolbert** [comment]
Hmm just seeing this now (apparent you don't auto-follow your own repos), sorry for the delay.

@carreau - no idea about the travis issue. If it becomes a problem, I can manually check in the typings.

**Comment by sccolbert** [comment]
@bollwyvl Those are pretty awesome!

**Comment by sccolbert** [comment]
@carreau - is this ready to go?

**Comment by Carreau** [comment]
Nah, I think I figured it out. Need to use a github token

**Comment by Carreau** [comment]
I'll try with one of my own token (just pushed) if ti work I'll create a token for Phosphor org, and replace it.

**Comment by Carreau** [comment]
Yeah!!! seem to build ! 

@sccolbert can you make me an admin or the org, even for a limitted amount of time so that I can enable travis on the master branch, and create a token for the org ?

**Comment by sccolbert** [comment]
@Carreau working on that now - quite a bit of waiting (probably due to DDOS)

**Comment by sccolbert** [comment]
for some reason travis is not syncing my repositories - it just hangs on the sync step and spews a bunch of errors to the console.

**Comment by Carreau** [comment]
I think DDoS is finished, but it's true that travis might be annoying when syncing sometimes.

**Comment by Carreau** [comment]
Added a tool to generate/encrypt ssh deploy keys on  a per repo basis. 

The token is still needed for `tsd` to not be rate limited by github.

**Comment by Carreau** [comment]
So of course my token is only decrypted on my repository... so annoying. Did you acchieve to encrypt one of your tokens ?

**Comment by sccolbert** [comment]
The Travis gem is broken on windows:
https://github.com/rubygems/rubygems/issues/1219

I'll have to fire up a vm.

**Comment by Carreau** [comment]
You can try https://www.npmjs.com/package/travis-encrypt I guess.

**Comment by sccolbert** [comment]
Can you retarget this PR to the feature-travis branch which I just created? I can merge that immediately and work on the token issue.

**Pull request closed without merging**
