### PR TITLE
try to autobuild docs on phosphor

### PR DESCRIPTION
**Pull request by Carreau**
Ok, first baby step, this **should** build the `/api/` path of the docs website, and deploy it.

### CODE REVIEW

**Comment by Carreau** [comment]
Major change is that it build docs in `./build/api` not in `./docs.` I can change that and make a `cp -r` as for examples. but that the kind of things I would prefer to refine with time to have a `-dev`api page, and a `-stable` api page.

**Comment by sccolbert** [comment]
can we change the output to `./build/docs`? To me, that's a bit more clear than `api`.

**Comment by Carreau** [comment]
yes done.

**Comment by sccolbert** [comment]
cheers!

**Pull request merged**
