### PR TITLE
Make formatKeystroke public

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Nice! Is do you have a target audience? The CalPoly interns working on the keyboard UI would be interested in this (which I suspect your reasoning?).

**Comment by blink1073** [comment]
My target audience was myself in JupyterLab. 😁

**Comment by ian-r-rose** [comment]
Right, I figured that out later as I progressed in my "morning Steve notifications". I had been after the interns to reuse the phosphor shortcut rendering, so it was on my mind.

**Comment by blink1073** [comment]
Great!

**Pull request merged**
