### PR TITLE
add drag-drop and mimedata modules

### PR DESCRIPTION
**Pull request by sccolbert**

### CODE REVIEW

**Comment by sccolbert** [comment]
Changes from `phosphor-dragdrop`:
- `DropAction` and `DropActions` enums are now the `DropAction` and `SupportedActions` string literal type aliases.
- `IDragOptions` -> `Drag.IOptions`
- `MimeData` is in a separate module: `core/mimedata.ts` so it can be reused for other things/libraries

**Comment by blink1073** [comment]
LGTM.

**Comment by afshin** [comment]
I'm pretty sure I asked in the original module, but since I don't remember the answer, perhaps it's better to ask here so that there will be a record of it. What's the reasoning again for having two arrays in `MimeData`, one for keys and one for values, instead of having a simple object: `{ [key: string]: any }`?

**Comment by sccolbert** [comment]
@afshin so that the return value of `types()` is always order of call to `setData()`.

**Comment by sccolbert** [comment]
The de facto standard for `Object.keys()` is order of insertion, but the real standard actually specifies it as undefined order. Not sure if order of insertion is maintained after deletes though.

**Comment by sccolbert** [comment]
In V8, it looks like only *initial* order of insertion is maintained:

```
> var a = {}
var a = {}
undefined
> a['1'] = 1
1
> a['2'] = 2
2
> a['3'] = 3
3
> Object.keys(a)
[ '1', '2', '3' ]
> delete a['2']
true
> Object.keys(a)
[ '1', '3' ]
> a['2'] = 2
2
> Object.keys(a)
[ '1', '2', '3' ]
```

**Comment by afshin** [comment]
Awesome, thanks for the explanation.

👍

**Comment by sccolbert** [comment]
If it ends up being a performance problem, we can change the internal data structure to something with better lookup characteristics. I doubt that will happen though, since the number of mime types used will normally only be a handful.

**Pull request merged**
