### PR TITLE
Add FlexPanel/FlexPanelLayout

### PR DESCRIPTION
**Pull request by vidartf**
Add a thin panel/layout for easy access to a CSS flexbox layout.

For just stacking like a normal panel, the default constructor is enough. For horizontal stacking, `new FlexPanel({direction: 'left-to-right'})`, and for evenly distributed children (evenly sized children) `new FlexPanel({evenSizes: true})`.

Discussion points that I want input on:
- [ ] Should the container (optionally) manage order as now implemented, or should this be set on individual widgets freely (maybe both, as long as they don't conflict)?
- [ ] If the current order management is kept, should the `moveWidget` implementation be kept as it is? This really relies if there are anything that relies on display order and widget sequence order being the same.
### TODO
- [ ] Tests
- [ ] Clean up docs to conform to same standard as the rest of phosphor (guidance welcome).

### CODE REVIEW

**Comment by vidartf** [comment]
Ref #51.

**Comment by vidartf** [comment]
Rebased and updated to be compatible with subfeatures.

**Comment by jasongrout** [comment]
> [vidartf](/vidartf) closed this [1 hour ago](#event-2403627146)

@vidartf - what advice would you give to someone that wanted to use flexbox, then? Just natively use flexbox in their CSS using a plain Panel?

**Comment by sccolbert** [comment]
@jasongrout Precisely. I'm not sure what wrapping the flexbox API gains us.

**Pull request closed without merging**
